$nat_setup_script = <<-NATSCRIPT
# allow forwarding and reload systemctl
echo 'net.ipv4.ip_forward = 1' > /etc/sysctl.d/net.ipv4.ip_forward.conf && sudo sysctl --system

# yum update
# yum -y update

# install epel-release and update CentOS
yum -y install epel-release

# install net-tools
yum -y install net-tools iptables-services

# enable/start iptables
systemctl start iptables && systemctl enable iptables

# add nat configuration to iptables
iptables -t nat -A POSTROUTING -j MASQUERADE
iptables -I FORWARD 1 -j ACCEPT

# stop/disable/mask firewalld
systemctl stop firewalld && systemctl disable firewalld && systemctl mask firewalld

NATSCRIPT

$netdata_setup_script = <<-NETDATA
yum -y install zlib-devel libuuid-devel libmnl-devel gcc make git autoconf autogen automake pkgconfig
yum -y install curl jq nodejs

cd /var/tmp

git clone https://github.com/firehol/netdata.git --depth=1
cd netdata
sudo ./netdata-installer.sh --dont-wait --install /opt

iptables -I INPUT 4 -p tcp -m multiport --dports 19999 -j ACCEPT

NETDATA

$client_setup_script = <<-CLIENTSCRIPT
ip route del default && ip route add default via 172.28.128.10 dev eth1
echo "DEFAULTROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth1
echo "ip route del default && ip route add default via 172.28.128.10 dev eth1" >> /etc/rc.local

CLIENTSCRIPT

$graphite_setup_script = <<-GRAPHITESCRIPT
yum -y install epel-release
yum -y install graphite-web python-carbon
GRAPHITESCRIPT

Vagrant.configure("2") do |config|

  config.vm.define "nat-node" do |node|
    node.vm.box      = "centos/7"
    node.vm.hostname = "nat-node"

    node.vm.network "private_network",
      ip: "172.28.128.10"
    node.vm.network "forwarded_port",
      guest: 19999, host: 19999

    node.vm.provision "shell",
      inline: $nat_setup_script
    node.vm.provision "shell",
      inline: $netdata_setup_script
  end

  (1..2).each do |i|
    config.vm.define "client0#{i}" do |c|
      c.vm.box      = "centos/7"
      c.vm.hostname = "client0#{i}"

      c.vm.network "private_network",
        ip: "172.28.128.2#{i}"

      c.vm.provision "shell",
        inline: $client_setup_script
    end
  end

  config.vm.define "graphite" do |g|
    g.vm.box      = "centos/7"
    g.vm.hostname = "graphite"

    g.vm.network "private_network",
      ip: "172.28.128.30"

    g.vm.provision "shell",
      inline: $graphite_setup_script
  end

end
